name: texta-toolkit
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - python=3.5
    - numpy
    - cython
    - scipy
    - gensim
    - django=2.1.5
    - sympy
    - lxml
    - beautifulsoup4
    - mysqlclient
    - psycopg2
    - graphviz
    - keras
    - pip:
        - python-logstash-async
        - sklearn
        - textract==1.5.0
        - dateparser
        - json2table
        - setuptools
        - wheel
        - requests
        - pathlib
        - dateutils
        - elasticsearch
        - elasticsearch_dsl
        - graypy
        - tensorflow
        - pydot
        - python-json-logger
        - git+https://github.com/autonomio/talos.git@daily-dev
